// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWeFnO622wLJXViNQrMEQ9num9lsKJa4',
    appId: '1:828600576143:web:40a69c5a3465e09332a8fa',
    messagingSenderId: '828600576143',
    projectId: 'recsseemflutter',
    authDomain: 'recsseemflutter.firebaseapp.com',
    storageBucket: 'recsseemflutter.appspot.com',
    measurementId: 'G-64FJRV11LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmCDHLahnv3XSYvFHP32bMFJa8MCS6Fs',
    appId: '1:828600576143:android:1b3dd7d1b586e4e132a8fa',
    messagingSenderId: '828600576143',
    projectId: 'recsseemflutter',
    storageBucket: 'recsseemflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xkoadeFJ1xTsSgktsRY_7202wcZj898',
    appId: '1:828600576143:ios:06c80faff768398032a8fa',
    messagingSenderId: '828600576143',
    projectId: 'recsseemflutter',
    storageBucket: 'recsseemflutter.appspot.com',
    iosClientId: '828600576143-j22pk5lenbldtud84md3a8ce2hqik52u.apps.googleusercontent.com',
    iosBundleId: 'com.example.recsseemMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4xkoadeFJ1xTsSgktsRY_7202wcZj898',
    appId: '1:828600576143:ios:06c80faff768398032a8fa',
    messagingSenderId: '828600576143',
    projectId: 'recsseemflutter',
    storageBucket: 'recsseemflutter.appspot.com',
    iosClientId: '828600576143-j22pk5lenbldtud84md3a8ce2hqik52u.apps.googleusercontent.com',
    iosBundleId: 'com.example.recsseemMobile',
  );
}
